# default config
gexs_csv: /mnt/fileserver/shared/datasets/biodata/MetaGX/merged/noNormMergedAnd10k.csv # gene expression data
treatments_csv: /mnt/fileserver/shared/datasets/biodata/MetaGX/mldata.csv
studies_csv:  /mnt/fileserver/shared/datasets/biodata/MetaGX/metaGXcovarTable.csv
normalization: True

latent_dim: 56 # dimensionality of the latent space
code_dim: 8 # latent code
n_classes: null # number of classes for dataset, infered from dataset but can be set here

n_epochs: 1200 # number of epochs of training
batch_size: 64 # size of the batches
lr: 0.0002 # adam: learning rate
b1: 0.5 # adam: decay of first order momentum of gradient
b2: 0.999 # adam: decay of first order momentum of gradient
